version: '3'  

services:
  web:  
    image: .  
    ports:
      - "81:5000"  

  db:  
    image: mysql  
    environment: 
      MYSQL_ROOT_PASSWORD: "your_password"
      MYSQL_DATABASE: "crud_db"
    volumes:
       - ./db:/docker-entrypoint-initdb.d/

